my_set_even = set(range(0, 101, 2))
print ("even numbers from 0-100: " + str(my_set_even))
print ("even numbers from 0-100 are : "+ str(len(my_set_even)) + " numbers")
my_set_odd = set(range(1, 101, 2))
print ("odd numbers from 0-100: " + str(my_set_odd))
print ("odd numbers from 0-100 are : "+ str(len(my_set_odd)) + " numbers")
my_set_multiple_3 = set(range(0, 101, 3))
print ("multiple 3 numbers from 0-100: " + str(my_set_multiple_3))
print ("multiple 3 numbers from 0-100 are : "+ str(len(my_set_multiple_3)) + " numbers")
